name: Compile Examples
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:nano:cpu=atmega168
          - arduino:avr:nano:cpu=atmega328
          - arduino:avr:mega:cpu=atmega1280
          - arduino:avr:mega:cpu=atmega2560
          - arduino:avr:leonardo

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            - examples/AnalogAndVoltage
            - examples/EEPROMCalibration
          
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: specification
